### ISSUE TITLE
Support for multiple databases

### ISSUE THREAD

**Issue by turgs** [teoljungberg/fx#155]
I'm using Rails 8 multiple databases. For primary I'm using postgres, but for cache and queues I'm using SQLite.

When trying to run migrations for _those_ databases, this gem looks to be intercepting

```
$ rails db:migrate:cache --trace
bin/rails aborted!
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: pg_proc (ActiveRecord::StatementInvalid)
Caused by:
SQLite3::SQLException: no such table: pg_proc (SQLite3::SQLException)
Tasks: TOP => db:schema:dump:errors
```

For now I've had to remove this gem as I can't figure out what monkey patch I need to do to try working around it. That said, I think it's similar to things mentioned here:
https://github.com/scenic-views/scenic/issues/402

**Comment by teoljungberg** [comment]
FX does not support sqlite, and while I get use-case for caching - I am not interested in having code find what is the database (in a set of mutliples) with a supported adapter.

**Comment by MaksJS** [comment]
@turgs I have the same issue, I've monkey-patched it this way:

```ruby
module Fx
    module Adapters
      module Postgres
        def functions
          return super if connection.adapter_name == 'PostgreSQL'

          []
        end

        def triggers
          return super if connection.adapter_name == 'PostgreSQL'

          []
        end
      end
    end
end
```

With the release of Rails 8, I think it will be more frequent and should be fixed at the gem level.

**Comment by teoljungberg** [comment]
If someone can come with a failing test setup for the dummy app inside the integration tests I'd look it over.

**Comment by MaksJS** [comment]
Heres a `config/database.yml` file example that would fail with Fx:

```yaml
default: &default
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

postgresql: &postgresql
  <<: *default
  adapter: postgresql

sqlite3: &sqlite3
  <<: *default
  adapter: sqlite3
  timeout: 5000

development:
  primary:[
    <<: *postgresql](adapter: postgresql)
    database: foo_development
  cable:
    <<: *sqlite3
    database: storage/development_cable.sqlite3
    migrations_paths: db/cable_migrate
  cache:
    <<: *sqlite3
    database: storage/development_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *sqlite3
    database: storage/development_queue.sqlite3
    migrations_paths: db/queue_migrate
```

When generating a new Fx function, it would go under `db/functions` and it will try to migrate it on the "queue" sqlite3 database for example.
