### ISSUE TITLE
Is the a proper way to update trigger functions?

### ISSUE THREAD

**Issue by XertroV** [teoljungberg/fx#75]
I think the right way to set up triggers with fx is like: (after running `fx:function` and then `fx:trigger` generators)

```yaml
db:
  functions:
    - do_the_thing_on_insert_v01.sql  # `CREATE OR REPLACE FUNCTION ...`
  triggers:
    - do_the_thing_on_insert_v01.sql  # `CREATE TRIGGER do_the_thing_on_insert AFTER ...`
```

then after running `rails g fx:function do_the_thing_on_insert` we have:

```yaml
db:
  functions:
    - do_the_thing_on_insert_v01.sql  # `CREATE OR REPLACE FUNCTION ...`
    - do_the_thing_on_insert_v02.sql  # `CREATE OR REPLACE FUNCTION ...`
  triggers:
    - do_the_thing_on_insert_v01.sql  # `CREATE TRIGGER do_the_thing_on_insert AFTER ...`
```

with the migration:

``` ruby
class UpdateFunctionDoTheThingOnInsertToVersion2 < ActiveRecord::Migration[6.1]
  def change
    update_function :do_the_thing_on_insert, version: 2, revert_to_version: 1
  end
end
```

that looks mb okay, but running it gives the error:

```
ActiveRecord::StatementInvalid: PG::DependentObjectsStillExist: ERROR:  cannot drop function do_the_thing_on_insert() because other objects depend on it
DETAIL:  trigger do_the_thing_on_insert on table things depends on function do_the_thing_on_insert()
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

I was hoping that the `CREATE OR REPLACE FUNCTION` thing would just work out, but apparently not. So the workaround I initially came up with was:

``` ruby
class UpdateFunctionDoTheThingOnInsertToVersion2 < ActiveRecord::Migration[6.1]
  def change
    drop_trigger :do_the_thing_on_insert, on: :things, revert_to_version: 1
    update_function :do_the_thing_on_insert, version: 2, revert_to_version: 1
    create_trigger :do_the_thing_on_insert, on: :things, version: 1
    raise "if we get here, the migration worked but don't commit the result, yet"
  end
end
```

however, this doesn't feel great, and only migrates correctly in the fwd direction. in the reverse I get:

```
-- drop_trigger(:do_the_thing_on_insert, {:on=>:things, :version=>2})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (given 2, expected 1; required keyword: on)
```

I can go the whole

```ruby
reversible do |dir|
  dir.up do; end
  dir.down do; end
end
```

But IDK if that's the *intended* way to do this sort of thing with fx. I had a look at other issues but didn't find anything.

Is there a better way to do this sort of thing? (or am I doing something wrong and can avoid this by doing something different?)
